### ISSUE TITLE
Unlanded human characters in Valinor

### ISSUE THREAD

**Issue by Remerod** [CK3RealmsinExile/RealmsInExile#886] opened 2023-05-03 14:57 UTC
It's been reported in the bug-report forum that some Unlanded human characters ends up in Valinor, i have doubled checked this and it is indeed so. So this is something that needs tweaking

Vector mentioned this:
> Probably just need to add a courtier cull event for any characters in Valinor on a yearly basis
Any non-Elves get DAS BOOT

![image](https://user-images.githubusercontent.com/79544635/235954817-c48ea6b6-095f-42ac-963e-1237098b7d1c.png)

**Comment by BriceLeduc** [comment] 2023-05-05 14:06
Probably linked to a missing trigger in an event, ready to test

**Comment by savagesach** [comment] 2023-08-13 04:59
![image](https://github.com/jj248/RealmsInExile/assets/86676697/6ebc39ce-c719-40ce-a295-a036575aa315)
finarfin's court is still being invaded by gondorians

**Comment by BriceLeduc** [comment] 2024-05-13 10:11
@Jaco-Daan didn't you solve this ?

**Comment by Jaco-Daan** [comment] 2024-07-17 20:47
This has been solved. The issue is courtiers not being assigned to ssomeone that is landed at game start

cloosing

**Closed by Jaco-Daan** 2024-07-17 20:47 UTC
Labels: Advanced Scripting
